end/demo/bookdemo/bookdemo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booktest.urls', namespace='booktest'))

]

end/demo/bookdemo/booktest/urls.py
# author:1zt
# date: 2020/2/14 10:01
# file_name: urls
# 引入路由
from django.conf.urls import url
from . import views

app_name = "booktest"
urlpatterns = [
    # url(r'^index/$', views.index),
    url(r'^$', views.index, name='index'),
    url(r'^detail/(\d+)/$', views.detail, name='detail'),
    url(r'^about/$', views.about, name='about'),
    url(r'^deletebook/(\d+)/$', views.deletebook, name='deletebook'),
    url(r'^addhero/(\d+)/$', views.addhero, name='addhero'),
    url(r'^deletehero/(\d+)/$', views.deletehero, name='deletehero')
]

end/demo/bookdemo/booktest/models.py
from django.db import models


# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length=20)
    price = models.FloatField(default=100)
    pub_date = models.DateField(default="1898-8-25")

    def __str__(self):
        return self.title


class Hero(models.Model):
    name = models.CharField(max_length=20)
    gender = models.CharField(max_length=10, choices=(('male', "男"), ('female', "女")), default="male")
    content = models.CharField(max_length=100)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

end/demo/bookdemo/booktest/views.py
from django.shortcuts import render, redirect, reverse

# Create your views here.

from django.http import HttpResponse
from django.template import loader
from .models import Book, Hero

from django.http import HttpResponseRedirect


def index(request):
    # return HttpResponse("这里是首页")
    # 1,获取模板
    # template = loader.get_template('index.html')
    # 2,渲染模板数据
    books = Book.objects.all()
    # context = {"books": books}
    # result = template.render(context)
    # return HttpResponse(result)

    return render(request, 'index.html', {"books": books})


def deletebook(request, bookid):
    book = Book.objects.get(id=bookid)
    book.delete()
    # return HttpResponse("删除成功")
    url = reverse("booktest:index")
    # return HttpResponseRedirect(redirect_to='/')
    return redirect(to=url)


def addhero(request, bookid):
    if request.method == "GET":
        return render(request, 'addhero.html')
    elif request.method == "POST":
        hero = Hero()
        hero.name = request.POST.get("heroname")
        hero.content = request.POST.get("herocontent")
        hero.gender = request.POST.get("sex")
        hero.book = Book.objects.get(id=bookid)
        hero.save()
        url = reverse("booktest:addhero", args=(bookid,))
        return redirect(to=url)


def deletehero(request, heroid):
    hero = Hero.objects.get(id=heroid)
    bookid = hero.bookid
    hero.delete()
    url = reverse("booktest:detail", args=(bookid,))
    return redirect(to=url)


def about(request):
    return HttpResponse("这里是关于页")


def detail(request, bookid):
    # return HttpResponse("这里是关于详情页" + bookid)
    # template = loader.get_template('detail.html')
    book = Book.objects.get(id=bookid)
    # context = {"book": book}
    # result = template.render(context)
    # return HttpResponse(result)

    return render(request, 'detail.html', {"book": book})

end/demo/bookdemo/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详情页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>


<body>
   <h1>这里是详情页</h1>
    <div>
        <h2>{{book.title}}</h2>
        <ul>
            {% for hero in book.hero_set.all %}
            <li>{{hero.name}} -- {{hero.gender}}--{{hero.content}}<a href="{% url 'booktest:deletehero' hero.id %}"></a></li>
            {% endfor %}
        </ul>
        <a href="{% url 'booktest:addhero' book.id %}">添加英雄</a>
    </div>
   <a href="{% url 'booktest:index' %}">返回列表页</a>
</body>
</html>

end/demo/bookdemo/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>

<body>
    <div class="container">
        <h1>这里是首页</h1>
        <div>
            <div class="center">
                <img src="/static/img/2.jpg" alt="">

            </div>
            <h2>所有的书籍{{books.count}}</h2>
            <u1>
                {% for book in books %}
                <li>
                    <a href="{% url 'booktest:detail' book.id %}">
                        {{book.id}}--{{book.title}}--{{book.price}}--{{book.pub_date}}
                    </a>
                    <a href="{% url 'booktest:deletebook' book.id %}">删除</a>
                </li>
                {% endfor %}
            </u1>
           {# <h2><a href="{% url 'booktest:addbook' %}">添加书籍</a></h2> #}
        </div>
    </div>

</body>
</html>